project:
  type: website
  output-dir: docs

website:
  title: "rMicrobe Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bib/index.qmd
        text: Rebecca's Site
      - href: tutorials/index.qmd
        text: rMicrobe Tutorials
      - href: illustrations/index.qmd
        text: TinyLife Illustrations
  search: true

format:
  html:
    toc: true
    code-line-numbers: true
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
          


